-- 0001_seed_baseline_data.sql
--
-- Baseline reference data that the application assumes exists in every
-- environment: the interest tag catalogue and the courage-message pool.
-- Idempotent via ON CONFLICT DO NOTHING so this migration can re-run on
-- an env that already has the rows (same release, different rollouts).
--
-- Future data changes (new tags, renames, deletions, new courage rows)
-- are separate migrations, not edits to this file. See docs/DATA_MIGRATIONS.md.

INSERT INTO "interest_tags" ("name", "slug") VALUES
  ('Vandring', 'vandring'),
  ('Fågelskådning', 'fagelskadning'),
  ('Trädgård', 'tradgard'),
  ('Fiske', 'fiske'),
  ('Jakt', 'jakt'),
  ('Paddling', 'paddling'),
  ('Camping', 'camping'),
  ('Geocaching', 'geocaching'),
  ('Paddleboard', 'paddleboard'),
  ('Ridning', 'ridning'),
  ('Promenad', 'promenad'),
  ('Löpning', 'lopning'),
  ('Cykling', 'cykling'),
  ('Simning', 'simning'),
  ('Yoga', 'yoga'),
  ('Dans', 'dans'),
  ('Kampsport', 'kampsport'),
  ('Styrketräning', 'styrketraning'),
  ('Klättring', 'klattring'),
  ('Padel', 'padel'),
  ('Tennis', 'tennis'),
  ('Golf', 'golf'),
  ('Bowling', 'bowling'),
  ('Skridskoåkning', 'skridskoakning'),
  ('Pilates', 'pilates'),
  ('Meditation', 'meditation'),
  ('Fotboll', 'fotboll'),
  ('Innebandy', 'innebandy'),
  ('Hockey', 'hockey'),
  ('Bandy', 'bandy'),
  ('Basket', 'basket'),
  ('Handboll', 'handboll'),
  ('Volleyboll', 'volleyboll'),
  ('Badminton', 'badminton'),
  ('Bordtennis', 'bordtennis'),
  ('Frisbee', 'frisbee'),
  ('Skateboard', 'skateboard'),
  ('Parkour', 'parkour'),
  ('Crossfit', 'crossfit'),
  ('Längdskidor', 'langdskidor'),
  ('Snowboard', 'snowboard'),
  ('Utförsåkning', 'utforsakning'),
  ('Extremsport', 'extremsport'),
  ('Gymnastik', 'gymnastik'),
  ('Paintball', 'paintball'),
  ('Airsoft', 'airsoft'),
  ('Sportskytte', 'sportskytte'),
  ('Fotografi', 'fotografi'),
  ('Målning', 'malning'),
  ('Keramik', 'keramik'),
  ('Sticka / Virka', 'sticka-virka'),
  ('Brodyr', 'brodyr'),
  ('Matlagning', 'matlagning'),
  ('Bakning', 'bakning'),
  ('Musik', 'musik'),
  ('Skrivande', 'skrivande'),
  ('Snickeri', 'snickeri'),
  ('Design', 'design'),
  ('Bilar', 'bilar'),
  ('Motorcykel', 'motorcykel'),
  ('Mekande', 'mekande'),
  ('Cruising', 'cruising'),
  ('Motorsport', 'motorsport'),
  ('EPA & A-traktor', 'epa-a-traktor'),
  ('Flyg', 'flyg'),
  ('Brädspel', 'bradspel'),
  ('Rollspel', 'rollspel'),
  ('Schack', 'schack'),
  ('E-sport', 'e-sport'),
  ('Modellbygge', 'modellbygge'),
  ('Lajv', 'lajv'),
  ('Figurspel', 'figurspel'),
  ('Datorspel', 'datorspel'),
  ('Bokcirkel', 'bokcirkel'),
  ('Film', 'film'),
  ('Vinprovning', 'vinprovning'),
  ('Språk', 'sprak'),
  ('Sportevent', 'sportevent'),
  ('Frivilligarbete', 'frivilligarbete'),
  ('Fika', 'fika'),
  ('Picknick', 'picknick'),
  ('Quiz', 'quiz'),
  ('Karaoke', 'karaoke'),
  ('Ölprovning', 'olprovning'),
  ('Restaurangbesök', 'restaurangbesok'),
  ('Resor', 'resor'),
  ('Teater', 'teater'),
  ('Konst', 'konst'),
  ('Historia', 'historia'),
  ('Stand-up', 'stand-up'),
  ('Utställning', 'utstallning'),
  ('Programmering', 'programmering'),
  ('Husdjur', 'husdjur')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO "courage_messages" ("audience", "message") VALUES
  ('alla', 'Du behöver inte känna någon för att komma, många som dyker upp gör det för första gången.'),
  ('alla', 'Alla är välkomna oavsett erfarenhet. Vi ses där!'),
  ('alla', 'Kom som du är. Det spelar ingen roll om du är nybörjare eller inte känner någon.'),
  ('alla', 'Jag startade den här aktiviteten just för att det ska vara lätt att hänga med. Välkommen!'),
  ('alla', 'Ingen förväntar sig att du redan kan allt. Kom och testa!'),
  ('alla', 'De flesta som kommer kände ingen första gången heller. Nu är de stammisar.'),
  ('par', 'Kom med en partner, en vän, en kollega. Alla sorts par är välkomna!'),
  ('par', 'Ni behöver inte ha provat detta förut. Kom som ni är!'),
  ('par', 'Perfekt att göra något nytt ihop, oavsett om ni är bästisar eller partners.'),
  ('par', 'Andra par som kommer är i samma sits. Nyfikna och redo att testa.'),
  ('par', 'Ta med dig någon du tycker om. Kompis, partner, syskon, spelar ingen roll.'),
  ('familj', 'Alla familjer är välkomna. Stora som små, en förälder eller två.'),
  ('familj', 'Barn i alla åldrar är välkomna. Vi anpassar efter gruppen!'),
  ('familj', 'Perfekt för familjer som vill prova något nytt ihop. Ensamstående föräldrar lika välkomna!'),
  ('familj', 'Andra familjer kommer också. Barnen brukar hitta kompisar snabbt.'),
  ('familj', 'Kom som er familj ser ut. Det enda som krävs är att ni vill ha kul tillsammans.')
ON CONFLICT (audience, message) DO NOTHING;
